### GET ALL ITEMS
GET http://localhost:8080/api/v1/doctors

###

### GET ONE ITEM
GET http://localhost:8080/api/v1/doctors/1

###

### DELETE ONE ITEM
DELETE http://localhost:8080/api/v1/items/3

###

### CREATE ONE ITEM
POST http://localhost:8080/api/v1/doctors
Content-Type: application/json

{
  "name": "Vitalina",
  "specialization": "surgeon",
  "description": "cool"
}
### UPDATE ONE ITEM
PUT http://localhost:8080/api/v1/doctors
Content-Type: application/json

{
  "id": "1",
  "name": "AliceCool",
  "specialization": "surgeon2",
  "description": "woow"
}


###

